name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        git clone git@github.com:zed-industries/zed.git
        cd zed
        cargo build --release --verbose
        tree zed
